[dev]
  command = "npm run --prefix web dev -- --port 5176"
  targetPort = 5176
  port = 8888
  framework = "#custom"

[build]
  command = "npm run build"
  publish = "web/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Proxy API route for production
[[redirects]]
  from = "/api/m365"
  to = "/.netlify/functions/m365"
  status = 200
  force = true

# Licensing serverless fetch
[[redirects]]
  from = "/api/licensing/fetch"
  to = "/.netlify/functions/licensing-fetch"
  status = 200
  force = true

# Solution Architecture endpoints
[[redirects]]
  from = "/api/sa/generate-options"
  to = "/.netlify/functions/sa-generate-options"
  status = 200
  force = true

[[redirects]]
  from = "/api/sa/hld-draft"
  to = "/.netlify/functions/sa-hld-draft"
  status = 200
  force = true

[[redirects]]
  from = "/api/sa/erd-draft"
  to = "/.netlify/functions/sa-erd-draft"
  status = 200
  force = true

[[redirects]]
  from = "/api/sa/generate-triple-options"
  to = "/.netlify/functions/sa-generate-triple-options"
  status = 200
  force = true

# AI utility endpoints
[[redirects]]
  from = "/api/ai/list-models"
  to = "/.netlify/functions/ai-list-models"
  status = 200
  force = true

[[redirects]]
  from = "/api/ai/discover"
  to = "/.netlify/functions/ai-discover-models"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
